"""empty message

Revision ID: cc245f7971d0
Revises: 9dacda6e54d3
Create Date: 2022-06-08 12:51:07.762192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc245f7971d0'
down_revision = '9dacda6e54d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), server_default='1', nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), server_default='1', nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_questions_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questions_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), server_default='1', nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['questions_id'], ['questions.id'], name=op.f('fk_answers_questions_id_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_answers_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answers'))
    )
    op.create_table('questions_voter',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('questions_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['questions_id'], ['questions.id'], name=op.f('fk_questions_voter_questions_id_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_questions_voter_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'questions_id', name=op.f('pk_questions_voter'))
    )
    op.create_table('answers_voter',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('answers_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answers_id'], ['answers.id'], name=op.f('fk_answers_voter_answers_id_answers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_answers_voter_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'answers_id', name=op.f('pk_answers_voter'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers_voter')
    op.drop_table('questions_voter')
    op.drop_table('answers')
    op.drop_table('questions')
    # ### end Alembic commands ###
